language: julia
os:
  - linux
julia:
  - 1.3
  - 1.4
  - nightly
matrix:
  allow_failures:
    - julia: nightly
notifications:
  email: false
after_success:
 - julia -e 'using Pkg; Pkg.add("Coverage"); cd(Pkg.dir("RandomMatrixDistributions")); Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
